server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/payment_db_ms?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112296root
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9096
  jpa:
    hibernate:
      ddl-auto: update
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  service-url: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


